### ISSUE TITLE
GetData RowTo

### ISSUE THREAD

**Issue by redowl3** [ipvalverde/EPPlus.DataExtractor#18]
If we want to read all rows how do we know the RowTo value of a file before uploading it?

**Comment by ipvalverde** [comment]
Hi @redowl3, you can put a custom function to one of your columns  (`WithProperty` method) and add a callback there that will abort the rest of the execution based on a condition. Check https://github.com/ipvalverde/EPPlus.DataExtractor/blob/master/README.md#callbacks


If one of your properties is required, you could check in the callback function if the cell value is empty/null and just abort the execution.

With that, your can set the `rowTo` of the `GetData` method to a value that you believe is big enough for your data set.
