### ISSUE TITLE
Upgrade EPPlus NuGet dependency

### ISSUE THREAD

**Issue by JohannZhu** [ipvalverde/EPPlus.DataExtractor#20]
I noticed that although the package's dependency description says it depends on EPPlus (>= 4.5.2.1), it actually depends on EPPlus (== 4.5.2.1) based on the code.

I am currently having problem with this since our projects are using EPPlus 4.5.3.2. which is the latest stable version.

I tried to download the solution and upgraded the package reference. All tests in EPPlus.DataExtractor.Tests work fine with EPPlus 4.5.3.2. 

Is it possible to modify the project in order to allow all EPPlus packages with version equal to or greater than 4.5.2.1?

**Comment by ipvalverde** [comment]
Sure, I works be happy to accept a pull request for that.

**Comment by JohannZhu** [comment]
Oh my bad.

The project is specifying its dependency in the correct way according to
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards

What I am really dealing with is "NuGet Hell":
https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts/

Sorry :)
