### ISSUE TITLE
Anonymous types

### ISSUE THREAD

**Issue by SilverSeva** [ipvalverde/EPPlus.DataExtractor#3]
Hi, good job with the DataExtractor!

But what about anonymous types? Can i simply extract all the data to List<object>?

What happen if i haven't any POCO class but want the data well formatted from the worksheet?

Regards

**Comment by ipvalverde** [comment]
Hi there, thank you!

I'm not sure how this would work, ask the "WithProperty" methods rely on the type previously specified to offer a hint on the property mapping with a cell.


I believe we could have something like:
    package.Workbook.Worksheets["worksheet1"]
        .Extract(data => 
            new
            {
                Name = data.GetColumn("A"),
                Age = data.GetColumn<int>("B")
                // ...
            })
            // ...



Do you have any API in mind on how your would like to use it without specifying a type?

**Comment by ipvalverde** [comment]
```csharp
package.Workbook.Worksheets["worksheet1"]
.Extract(data =>
new
{
Name = data.GetColumn("A"),
Age = data.GetColumn("B")
// ...
})
// ...
```

**Comment by xavave** [comment]
Hi ipalverde, 
this is an excellent project !
How can I achieve this ?
 1) WithCollectionProperty : I need to extract 2 columns , not just one : Id and Value
 in screenshot : Id is RMID and value is : weight
2) I don't know by advance how many columns ID,value I can have , I would need to iterate through columns untill column name is empty
![example](https://user-images.githubusercontent.com/3501675/37873215-f7a7dd9c-3017-11e8-8f19-d8a14731e9ef.PNG)

**Comment by ipvalverde** [comment]
Closed due to inactivity.
