### ISSUE TITLE
extended WithCollectionProperty

### ISSUE THREAD

**Issue by xavave** [ipvalverde/EPPlus.DataExtractor#8]
Hi ipalverde,
this is an excellent project !
This is not an issue, it's an improvment request  

How can I achieve this ?

1. WithCollectionProperty : I need to extract 2 columns , not just one : Id and Value
in screenshot : Id is RMID and value is : RM poids
2. I don't know by advance how many columns ID,value I can have , I would need to iterate through columns untill column name is empty
![example](https://user-images.githubusercontent.com/3501675/37873291-07d4ea96-301a-11e8-8816-1a977bed6c02.PNG)
I've tried to customize your code but I can't get it to work:
![example2](https://user-images.githubusercontent.com/3501675/37873294-10021aa4-301a-11e8-9759-3ee2eacb04a9.PNG)
![example3](https://user-images.githubusercontent.com/3501675/37873295-1278706c-301a-11e8-9d82-c8e7bbb82034.PNG)

**Comment by xavave** [comment]
I could finally figure it out like that  : 
` var fileInfo = GetSpreadsheetFileInfo();
            using (var package = new ExcelPackage(fileInfo))
            {
                var data = package.Workbook.Worksheets["Laboratory"]
                    .Extract<RowDataWithColumnBeingRow>()
                    .WithProperty(p => p.Name, "B")
                    .WithProperty(p => p.Code, "C")
                    .WithCollectionProperty(p => p.MyCustomData,
                        item => item.id, 1,
                          item => item.Weight,
                          item => item.id,
                        item => item.Weight, "F", "AK"
                       )
                    .GetData(2, 4, 2)
                    .ToList();
}`

with MyCustomData defined as : 
`public class ColumnData
        {
            public string Weight { get; set; }

            public string id { get; set; }
        }`

and 
`public void SetPropertyValue(TRow dataInstance, int row, ExcelRange cellRange)
        {
            var collection = new TCollection();

            foreach (var cell in cellRange[this.initialColumn + row + ":" + this.finalColumn + row])
            {
                if (cell.Start.Column % 2 == 0)
                {
                    var collectionItem = new TCollectionItem();

                    // cell here will be a single cell, always.
                    // So I get the column from that cell in order to obtain the header.
                    int column = cell.Start.Column;
                    var nextCell = cellRange[cell.Start.Row, column + 1];
                    this.collectionItemHeadPropertySetter.SetPropertyValue(collectionItem, cellRange[this.headerRow, column]);
                    this.collectionItemHeadPropertySetter2.SetPropertyValue(collectionItem, cellRange[this.headerRow2, column + 1]);

                    this.collectionItemRowPropertySetter.SetPropertyValue(collectionItem, cell);
                    this.collectionItemRowPropertySetter2.SetPropertyValue(collectionItem, nextCell);

                    collection.Add(collectionItem);
                }
            }

            this.setCollectionProperty(dataInstance, collection);
        }
    }`

btw I removed headerRow2; 

this solution is not an optimal one, but at least it works for my current requirements

**Comment by xavave** [comment]
I've updated the code again so I can be able to set different types to id and value:

        public class ColumnData
        {
            public double Weight { get; set; }

            public int id { get; set; }
        }

and 

            var fileInfo = GetSpreadsheetFileInfo();
            using (var package = new ExcelPackage(fileInfo))
            {
                var data = package.Workbook.Worksheets["Laboratory 4 (Formule)"]
                    .Extract<RowDataWithColumnBeingRow>()
                    .WithProperty(p => p.Name, "B")
                    .WithProperty(p => p.Code, "C")
                    .WithCollectionProperty(p => p.MyCustomData,
                        item => item.id, item => item.Weight, 1,
                          item => item.id,
                        item => item.Weight, "F", "AK"
                       )
                    .GetData(2, 4, 2) //last "2" is step to skip 1 column on each iteration
                    .ToList();
    }

with 

        ICollectionPropertyConfiguration<TRow> WithCollectionProperty<TCollectionItem, THeaderValue, THeaderValue2, TRowValue, TRowValue2>(
            Expression<Func<TRow, List<TCollectionItem>>> propertyCollection,
            Expression<Func<TCollectionItem, THeaderValue>> headerProperty, 
    Expression<Func<TCollectionItem, THeaderValue2>> headerProperty2,
     int headerRow,

            Expression<Func<TCollectionItem, TRowValue>> rowProperty,
            Expression<Func<TCollectionItem, TRowValue2>> rowProperty2,
            string startColumn, string endColumn)
            where TCollectionItem : class, new();

as i have no constructor with cellValueConverter , I've made a quick hack :

        bool IsDigitsOnly(string str)
        {
            foreach (char c in str)
            {
                if (c < '0' || c > '9')
                    return false;
            }
            return true;
        }


and

        protected bool SetPropertyValue(TModel dataInstance, ExcelRangeBase cell)
        {
            // This instance should be created only if there is at least one callback function defined.
            var context = (this.validateValue != null || this.validateCastedValue != null) ?
                new PropertyExtractionContext(new CellAddress(cell))
                :
                null;

            if (this.validateValue != null)
            {
                this.validateValue(context, cell.Value);
                if (context.Aborted)
                    return false;
            }
            TValue value;
            if (cellValueConverter == null)
            {
                var cellText = cell.Text.Trim().Replace(",", "").Replace(".", "");
                if (IsDigitsOnly(cellText))
                    cell.Value = double.Parse(cell.Text.Trim().Replace(",", "."));
                value = cell.GetValue<TValue>();

            }
            else
                value = this.cellValueConverter(cell.Value);

            if (this.validateCastedValue != null)
            {
                this.validateCastedValue(context, value);
                if (context.Aborted)
                    return false;
            }

            setPropertyValueAction(dataInstance, value);
            return true;
        }

but I'm sure that you would have a cleaner and more simple solution

**Comment by ipvalverde** [comment]
Hi @xavave , I'm glad this library is being useful to you.


I think I've found a generic solution for this problem. Let me know if an API like this would suffice for your requirements.

Considering a model like this:
```csharp
public class MyRowModel
{
    public string Code { get; set; }
    public DateTime UpdateDate { get; set; }
    public string Comments { get; set; }
    public List<RmInfo> Rms { get; set; }
}
public class RmInfo
{
    public string Id { get; set; }
    public string PoIds { get; set; }
}
```
The code for extracting the data would be:
```csharp
                var data = package.Workbook.Worksheets["MyWorksheet"]
                    .Extract<MyRowModel>()
                    .WithProperty(p => p.Code, "C")
                    .WithProperty(p => p.UpdateDate, "D")
                    .WithProperty(p => p.Comments, "E")

                   // New overload:
                    .WithCollectionProperty(p => p.Rms,
                        1, // The index of the row where the "header" is located
                        "C", // The column letter indicating where this collection starts

                        // This is an action with a parameter that can be used to configure the
                       // columns for the collection (property "Rms")
                        cfg => cfg
                                .WithProperty(rmInfo => rmInfo.Id, "RM ID") // Maps a property to the column header
                                .WithProperty(rmInfo=> rmInfo.PoIds, "RM poids"))
                               // Finishes the "WithCollectionProperty" method call
                    .GetData(2, 4)
                    .ToList();
```

In this example, the extractor will start looking for columns with a header that matches the ones configured in the *inner WithProperty* methods ("RM ID" and "RM poids"). This search will start in the column "C" and it will go on until there are no more cells with text.
Another option would be to stop looking if the column text does not match any of the properties configured.

I expect to have this published in a new beta release by Monday.

**Comment by xavave** [comment]
Yes, it's exactly what I need , thank you so much !
 I was currently modifing your source code , I was in need for 3 nested columns and 1 convertdatafunc for each nested column, so I have added :

        ICollectionPropertyConfiguration<TRow> WithCollectionProperty<TCollectionItem, THeaderValue, THeaderValue2, THeaderValue3, TRowValue, TRowValue2, TRowValue3>(
            Expression<Func<TRow, List<TCollectionItem>>> propertyCollection,
            Expression<Func<TCollectionItem, THeaderValue>> headerProperty, Expression<Func<TCollectionItem, THeaderValue2>> headerProperty2,
             Expression<Func<TCollectionItem, THeaderValue3>> headerProperty3,
            int headerRow,
            Expression<Func<TCollectionItem, TRowValue>> rowProperty,
            Expression<Func<TCollectionItem, TRowValue2>> rowProperty2,
            Expression<Func<TCollectionItem, TRowValue3>> rowProperty3,
              Func<object, TRowValue> convertDataFunc1,
            Func<object, TRowValue2> convertDataFunc2,
            Func<object, TRowValue3> convertDataFunc3,
            string startColumn, string endColumn)
            where TCollectionItem : class, new();

but your solution is much better

**Comment by ipvalverde** [comment]
Hi @xavave I just published the version [2.0.0-alpha2](https://www.nuget.org/packages/EPPlus.DataExtractor/2.0.0-alpha0002). There is no documentation yet but you can check [this unit test](https://github.com/ipvalverde/EPPlus.DataExtractor/blob/2.0.0-alpha2/src/EPPlus.DataExtractor.Tests/WorksheetExtensionsTests.cs#L276) with an example. The spreadsheet can be download [from here](https://github.com/ipvalverde/EPPlus.DataExtractor/blob/2.0.0-alpha2/src/EPPlus.DataExtractor.Tests/spreadsheets/WorkbookTest.xlsx).

**Comment by xavave** [comment]
Hi Israel

Thnak you for this new release :)

However, I have some issues : cannot infer type arguments for withproperty

so I've tried

but error: cfg (of type monthlyrevenue) does not contain definition for
withproperty

should I cast cfg to a specific interface or make cfg inherit from a data
extractor interface ?
I've tried


​and

​

​






​
​did I miss something ?​


*Xavier AVERBOUCH*

Port. : +33(0)6 63 53 84 27


2018-03-27 0:25 GMT+02:00 Israel Valverde <notifications@github.com>:

**Comment by ipvalverde** [comment]
Sorry @xavave , I can't see your screenshots. I've noticed that I only implemented support for the `List<T>` type property.

Can you make sure that:
- You are referencing the latest version (2.0.0-alpha0002);
- The collection property of your model is of type `List<T>`;

If the problem still persists, could you provide a small fully-functional sample of code where I can reproduce it (in a github repository, or just pasting the code into the comments)?

**Comment by xavave** [comment]
I've also sent the mail with screenshots on your mail :
israelpereiravalverde@gmail.com, Can see them on your gmail ?


*Xavier AVERBOUCH*

Port. : +33(0)6 63 53 84 27


2018-03-27 9:44 GMT+02:00 Israel Valverde <notifications@github.com>:

**Comment by xavave** [comment]
I've just added to the 2.0.0-alpha0002 :

     [Fact]
        public void ExtractDataTransformingAGroupOfColumnsIntoRows()
        {
            var fileInfo = GetSpreadsheetFileInfo();
            using (var package = new ExcelPackage(fileInfo))
            {
                var data = package.Workbook.Worksheets["ColumnsGroupsAsRowsWorksheet"]
                    .Extract<CarDealerBranchRevenue>()
                    .WithProperty(p => p.BranchName, "A")
                    .WithProperty(p => p.BranchLocation, "B")
                    .WithCollectionProperty(p => p.RevenueByMonth,
                        1,
                        "C",
                        cfg => cfg
                                .WithProperty(revenueByMonth => revenueByMonth.Month, "Month")
                                .WithProperty(revenueByMonth => revenueByMonth.Revenue, "Revenue"))
                    .GetData(2, 3)
                    .ToList();

                Assert.Equal(2, data.Count);

                Assert.True(data.All(i => i.RevenueByMonth.Count == 4));

                {
                    var seattleBranch = data.SingleOrDefault(i => i.BranchName == "Seattle local car dealer" && i.BranchLocation == "Seattle, WA");
                    Assert.NotNull(seattleBranch);
                    Assert.NotEmpty(seattleBranch.RevenueByMonth);
                    Assert.Equal(4, seattleBranch.RevenueByMonth.Count);
                    Assert.Contains(seattleBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "January" && revenueBymonth.Revenue == 57000);
                    Assert.Contains(seattleBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "February" && revenueBymonth.Revenue == 100000);
                    Assert.Contains(seattleBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "March" && revenueBymonth.Revenue == -300);
                    Assert.Contains(seattleBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "April" && revenueBymonth.Revenue == 95420.45m);
                }

                {
                    var newYorkBranch = data.SingleOrDefault(i => i.BranchName == "Liberty autos" && i.BranchLocation == "New York, NY");
                    Assert.NotNull(newYorkBranch);
                    Assert.NotEmpty(newYorkBranch.RevenueByMonth);
                    Assert.Equal(4, newYorkBranch.RevenueByMonth.Count);
                    Assert.Contains(newYorkBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "March" && revenueBymonth.Revenue == 500000);
                    Assert.Contains(newYorkBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "April" && revenueBymonth.Revenue == 1200000);
                    Assert.Contains(newYorkBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "May" && revenueBymonth.Revenue == 100000);
                    Assert.Contains(newYorkBranch.RevenueByMonth, revenueBymonth => revenueBymonth.Month == "August" && revenueBymonth.Revenue == 325000);
                }
            }

and also 

    public class CarDealerBranchRevenue
        {
            public string BranchName { get; set; }
            public string BranchLocation { get; set; }

            public List<MonthlyRevenue> RevenueByMonth { get; set; }

            public class MonthlyRevenue
            {
                public string Month { get; set; }

                public decimal Revenue { get; set; }
            }
        }

but I get a compilation error :

    Error	CS1061	'WorksheetExtensionsTests.CarDealerBranchRevenue.MonthlyRevenue' does not contain a definition for 'WithProperty' and no extension method 'WithProperty' accepting a first argument of type 'WorksheetExtensionsTests.CarDealerBranchRevenue.MonthlyRevenue' could be found (are you missing a using directive or an assembly reference?)	EPPlus.DataExtractor.Tests	C:\work\EPPlus.DataExtractorBeta\src\EPPlus.DataExtractor.Tests\WorksheetExtensionsTests.cs	286	Active

**Comment by xavave** [comment]
Hi
I just had to add a new contructor with convertDataFunc to fullfill my requirments:
in ICollectionPropertyConfiguration:

      IColumnToCollectionConfiguration<TCollectionItem> WithProperty<TColumnValue>(
       Expression<Func<TCollectionItem, TColumnValue>> columnValueProperty, string columnHeader, 
    Func<object, TColumnValue> convertDataFunc);

then in class ColumnToCollectionConfiguration:

            public IColumnToCollectionConfiguration<TCollectionItem> WithProperty<TColumnValue>(
       Expression<Func<TCollectionItem, TColumnValue>> columnValueProperty, string columnHeader, Func<object, TColumnValue> convertDataFunc)
        {
            var dataExtractor = new RowDataExtractor<TCollectionItem, TColumnValue>(columnValueProperty, convertDataFunc);

            this.propertiesSettersByHeader.Add(columnHeader, dataExtractor);

            return this;
        }

and  in RowDataExtractor : 

    internal class RowDataExtractor<TModel, TValue> : PropertyValueSetter<TModel, TValue>,
        IRowDataExtractor<TModel>
        where TModel : class, new()
    {
        public RowDataExtractor(Expression<Func<TModel, TValue>> propertyExpression, Func<object, TValue> convertDataFunc) : base(propertyExpression, convertDataFunc, null, null)
        {}

        void IRowDataExtractor<TModel>.SetPropertyValue(TModel dataInstance, ExcelRangeBase cellRange)
        {
            base.SetPropertyValue(dataInstance, cellRange);
        }
    }

**Comment by xavave** [comment]
Would it be also possible to add 2 collection properties like this ? (the prices2 collection should be added to price1 collection as price1 and price2 are 2 distinct "Price" instances)
when I try this below, I get a compilation error on the first  cfg2.WithProperty:

Error	CS1061	'Price' does not contain a definition for 'WithProperty' and no extension method 'WithProperty' accepting a first argument of type 'Price' could be found (are you missing a using directive or an assembly reference?)	


      .WithCollectionProperty(p => p.Prices, 1, "A",
     cfg => cfg
     .WithProperty(pr => pr.RawMaterialId, "Index")
     .WithProperty(pr => pr.PriceValue, "price1", fnConvertPrice))
     .WithCollectionProperty(p => p.Prices, 1, "A",
     cfg2 => cfg2
     .WithProperty(pr => pr.RawMaterialId, "Index")
     .WithProperty(pr => pr.PriceValue, "price2", fnConvertPrice)
     )

**Comment by xavave** [comment]
A good point would be also to map a "static" object not relate to excel : e.g.:  .WithProperty(pr => pr.PriceCurrencyId, 1) below:

    .WithCollectionProperty(p => p.Prices, 1, "A",
    cfg => cfg
    .WithProperty(pr => pr.RawMaterialId, "Index")
    .WithProperty(pr => pr.PriceCurrencyId, 1)
     .WithProperty(pr => pr.PriceValue, "price1", fnConvertPrice)

**Comment by xavave** [comment]
I've also noticed a possible issue :

I'm importing some prices  and PriceValue (of type double) is filled with the good value from excel:
 
        var importedPrices2 = ws.Extract<Price>()
              .WithProperty(p => p.RawMaterialId, "A")
              .WithProperty(p => p.PriceValue, "S", fnConvertPrice)
               .GetData(2, (row) => ws.Cells[row, 2].Value != null).ToList();

but if I do the same with :

        var importedRawMaterials = ws.Extract<RawMaterial>()
        .WithProperty(...)
       .WithProperty(...)
        .WithProperty(...)
      .WithCollectionProperty(p => p.Prices, 1, "A",
       cfg => cfg
       .WithProperty(pr => pr.RawMaterialId, "Index")
       .WithProperty(pr => pr.PriceValue, "price1", fnConvertPrice)
      ).GetData(2, (row) => ws.Cells[row, 2].Value != null).Where(s => s.Id > -1).ToList();


![image](https://user-images.githubusercontent.com/3501675/38026287-dc187e3a-328b-11e8-8166-e7766a9d19b8.png)

     var newList = importedRawMaterials.ToList());
  but  

     newList .First().Prices.First().PriceValue== 0;//all "PriceValues" are equal 0 (but not supposed to be so)
![image](https://user-images.githubusercontent.com/3501675/38026394-37cec450-328c-11e8-8ac5-b129657c04db.png)

The PriceValue as been lost after ToList() call
when I put a break point on fnConvertPrice, the value is filled correctly

If I don't use fnConvertPrice, I get the same issue

![image](https://user-images.githubusercontent.com/3501675/38026134-396cce34-328b-11e8-84e6-63d5d2cd8fa8.png)

![image](https://user-images.githubusercontent.com/3501675/38026160-55bd2ea8-328b-11e8-9d9a-3ca18137e05c.png)

![image](https://user-images.githubusercontent.com/3501675/38026203-80f682a4-328b-11e8-8e66-406d83b89840.png)
